# Generated by Django 5.2 on 2025-04-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
